# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43cee868b75e9c6ce0667e48f87674c6f30096e5769e57ca70cc4d01b0d533c6b7c7efb368914e757839f1e26758ee0b810a9ea19499c363ae340e829634d297

test:
  secret_key_base: f9c6c7024c28b430fbfc835f9faf47d5174e24bd7b555f2eba11c6474854a8936f4af3e89b2218f3eb8904656459c1f1e6d3d3c6ee4a7735634118e8295582e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: zd28rigo96